version: '3'
services:
#mssql docker
  eautokuca-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Naila123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - eautokucanet
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - eautokucanet
  
  eautokuca-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=eautokuca-sql,1433;Database=eAutoKucaDatabase;User=sa;Password=Naila123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - SERVER_ADDRESS=smtp.gmail.com
      - MAIL_SENDER=autokucalena@gmail.com
      - MAIL_PASS=iszgskdnofylaxqo
      - MAIL_PORT=587
    ports:
      - 5146:5146
    networks:
      - eautokucanet
    links:
      - eautokuca-sql
    depends_on:
      - eautokuca-sql
      - rabbitmq

  eautokuca-console:
    restart: unless-stopped
    build:
      context: ./eAutokucaRabbitMQ
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - SERVER_ADDRESS=smtp.gmail.com
      - MAIL_SENDER=autokucalena@gmail.com
      - MAIL_PASS=iszgskdnofylaxqo
      - MAIL_PORT=587
    networks:
      - eautokucanet
    depends_on:
      - rabbitmq
 
networks:
  eautokucanet:
    driver: bridge 