version: '3'
services:
#mssql docker
  eautokuca-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Naila123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - eautokucanet
    
  

  eautokuca-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=eautokuca-sql,1433;Database=eAutoKucaDatabase;User=sa;Password=Naila123!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5146:5146
    networks:
      - eautokucanet
    links:
      - eautokuca-sql
    depends_on:
      - eautokuca-sql

  
 
      
networks:
  eautokucanet:
    driver: bridge 